apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo-app
type: Opaque
data:
  mongo-root-username: cm9vdA==

  mongo-root-password: ZXhhbXBsZQ==

  MONGO_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nb2RiLXNlcnZpY2U6MjcwMTcvbXVjaF90b2RvX2RiP2F1dGhTb3VyY2U9YWRtaW4=

