apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: muchtodo-app
spec:
  # type: ClusterIP
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
     # nodePort: 30081